$(document).ready(function(){
    $("#design").click(function(){
        $("#design").hide();
        $("#anny").show();
    });
    $("#anny").click(function(){
        $("#anny").hide();
        $("#design").show();
    });
     $("#develop").click(function(){
        $("#develop").hide();
    $("#anit").show();
    });
     $("#anit").click(function(){
        $("#anit").hide();
        $("#develop").show();
    });
    $("#product").click(function(){
        $("#anitha").hide();
       $("#product").show();
    });
    $("#anitha").click(function(){
       $("#anitha").hide();
      $("#product").show();
     });
});